name: 'setup-gradlew'
description: 'Checkout code and setup gradlew'

inputs:
  token:
    description: 'Github token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout current code
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

    - name: Add execute permissions to gradle
      shell: bash
      run: chmod +x gradlew
