/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bio.terra.aws.resource.discovery;

public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
