# This action must be done after the checkout action
name: 'bump-skip'
description: 'Set skip-out when we are doing a version bump'

inputs:
  event-name:
    description: 'Github event name'
    required: true

outputs:
  is-bump:
    description: 'yes if this is a push made by bumper; no if it is a regular push'
    value: ${{ steps.bump-test.outputs.is-bump }}

runs:
  using: 'composite'

  steps:
    - name: Bump test
      id: bump-test
      shell: bash
      run: |
        log=$(git log --pretty='%B')
        echo "log=$log"
        pattern="^bump .*"
        IS_BUMP=no
        if [[ "${{ inputs.event-name }}" == "push" && "$log" =~ $pattern ]]; then
          IS_BUMP=yes
        fi
        echo "is-bump=$IS_BUMP"
        echo is-bump=$IS_BUMP >> $GITHUB_OUTPUT
