name: Build and Run Tests

on:
  workflow_dispatch: {}
  # TODO(TERRA-400): Set up test-on-push when repo is ready
  # push:
    # branches: [ main ]
    # paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Setup gradlew
        uses: ./.github/actions/setup-gradlew

      - name: Run linter
        id: linter
        run: ./gradlew spotlessCheck

      - name: Run static analysis
        id: static-analysis
        run: ./gradlew spotbugsMain spotbugsTest

      - name: Build, assemble, and test
        id: build-test
        run: ./gradlew build --scan

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports
          path: build/reports
