name: Build and Run Tests

on:
  workflow_dispatch: {}
  # push:
    # branches: [ main ]
    # paths-ignore: [ '**.md' ]
  pull_request:
    # Branch settings require status checks before merging, so don't add paths-ignore.
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          ./gradlew spotlessCheck
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build, assemble, and test
        id: build-test
        run: ./gradlew build --scan
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Test Reports
          path: build/reports
