name: Publish to Artifactory

on:
  workflow_call:
    inputs:
      artifactory-repo-key:
        description: 'Artifactory repository key'
        type: string
        required: true
      subproject:
        description: 'Subproject at the repository root'
        type: string
        required: false

jobs:
  publish-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout current code & setup gradlew
        id: setup-gradlew
        uses: ./.github/actions/setup-gradlew
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Fetch latest tags
        id: git-pull
        run: git pull
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}

      - name: Publish to artifactory
        run: ./gradlew ${{ inputs.subproject }}:artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: ${{ inputs.artifactory-repo-key }}
