name: Publish to Artifactory

on:
  workflow_call:
    inputs:
      artifactory_repo_key:
        description: 'Artifactory repository key'
        type: string
        required: true
      subproject:
        description: 'Subproject at the repository root'
        type: string
        required: false

jobs:
  publish-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Fetch latest tags
        id: git-pull
        run: |
          git pull
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

      - name: Publish to Artifactory
        run: |
          chmod +x gradlew
          ./gradlew ${{ inputs.subproject }}:artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: ${{ inputs.artifactory_repo_key }}
