name: Publish

on:
  workflow_call:
    inputs:
      artifactory_repo_key:
        description: 'Artifactory repository key'
        type: string
        required: true
      subproject:
        description: 'Subproject at the repository root'
        type: string
        required: false

jobs:
  publish-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish to Artifactory
        run: ./gradlew ${{ github.event.inputs.subproject }}:artifactoryPublish
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO_KEY: ${{ github.event.inputs.artifactory_repo_key }}
