name: Tag, publish

# TODO: Set up publish-on-push when repo is ready
on:
  workflow_dispatch: {}
  #push:
  #  branches: [ main ]
  #  paths-ignore: [ '**.md' ]

jobs:
  tag:
    uses: ./.github/workflows/tag.yml
    secrets: inherit

  publish:
    needs: [ tag ]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      artifactory_repo_key: libs-snapshot-local
