name: Tag, publish

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Type of bump'
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

jobs:
  tag:
    if: "!contains( github.event.sender.login, 'broadbot')"
    uses: ./.github/workflows/tag.yml
    secrets: inherit
    with:
      with-v: true

  release:
    needs: [ tag ]
    if: ${{ needs.tag.outputs.tag }} != ""
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      tag: ${{ needs.tag.outputs.tag }}
      overwrite: true

  publish:
    needs: [ tag ]
    if: ${{ needs.tag.outputs.tag }} != ""
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      artifactory-repo-key: 'libs-snapshot-local'

  alias-tags:
    needs: [ tag ]
    if: ${{ needs.tag.outputs.tag }} != ""
    uses: ./.github/workflows/alias-tags.yml
    secrets: inherit
    with:
      semverTag: ${{ needs.tag.outputs.tag }}

  alias-release-minor:
    needs: [ alias-tags ]
    if: ${{ needs.alias-tags.outputs.minor-version-alias }} != ""
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      tag: ${{ needs.alias-tags.outputs.minor-version-alias }}

  alias-release-major:
    needs: [ alias-tags ]
    if: ${{ needs.alias-tags.outputs.major-version-alias }} != ""
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      tag: ${{ needs.alias-tags.outputs.major-version-alias }}
