name: (Reusable workflow) Generate a new Tag

on:
  workflow_call:
    inputs:
      bump-type:
        description: 'Type of bump'
        type: string
        required: false
        default: patch
      hotfix-branches:
        description: 'Name of the hotfix branch'
        type: string
        required: false
        default: hotfix.*
      release-branches:
        description: 'Release branch'
        type: string
        required: false
        default: main
      version-file-path:
        description: 'Path to file containing the version string'
        type: string
        required: false
        default: settings.gradle
      version-line-match:
        description: 'Line containing the version string'
        type: string
        required: false
        default: "^\\s*gradle.ext.version\\s*=\\s*'.*'"
      version-suffix:
        description: 'Version suffix'
        type: string
        required: false
      with-v:
        description: 'Tag version with v character'
        type: boolean
        required: false
        default: false

    outputs:
      tag:
        description: 'Generated tag'
        value: ${{ jobs.tag-job.outputs.tag }}

jobs:
  tag-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      is-bump: ${{ steps.bump-skip.outputs.is-bump }}

    steps:
      - name: Checkout current code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BROADBOT_TOKEN }}

      - name: Skip version bump merges
        id: bump-skip
        uses: ./.github/actions/bump-skip
        with:
          event-name: ${{ github.event_name }}

      - name: Set part of semantic version to bump
        if: steps.bump-skip.outputs.is-bump == 'no'
        id: semver-check
        run: |
          SEMVER_PART=${{ inputs.bump-type }}
          if ${{github.event_name == 'push' }}; then
            SEMVER_PART='patch'
          fi
          echo semver-part=$SEMVER_PART >> $GITHUB_OUTPUT

      - name: Bump the tag to a new version
        if: steps.bump-skip.outputs.is-bump == 'no'
        uses: databiosphere/github-actions/actions/bumper@bumper-0.1.0
        id: tag
        env:
          DEFAULT_BUMP: ${{ inputs.bump-type }}
          GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
          HOTFIX_BRANCHES: ${{ inputs.hotfix-branches }}
          OVERRIDE_BUMP: ${{ steps.semver-check.outputs.semver-part }}
          RELEASE_BRANCHES: ${{ inputs.release-branches }}
          VERSION_FILE_PATH: ${{ inputs.version-file-path }}
          VERSION_LINE_MATCH: ${{ inputs.version-line-match }}
          VERSION_SUFFIX: ${{ inputs.version-suffix }}
          WITH_V: ${{ inputs.with-v }}
